set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_ENV_PASSTHROUGH CCP_EVE_PERFORCE_BRANCH_PATH)
set(VCPKG_BUILD_TYPE release)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES "arm64;x86_64")
set(VCPKG_OSX_DEPLOYMENT_TARGET 10.15)

if (PORT MATCHES "bsdiff-drake127")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()

if (PORT MATCHES "yaml-cpp")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()

if (PORT MATCHES "curl")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()

if (PORT MATCHES "zlib")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()